version: "3.8"

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admmin0A
      POSTGRES_DB: tienda
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data